name: flutter_pinterestclone
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.2
  provider: 6.0.4
  http: 0.13.5
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: 3.2.2
  lottie: 2.2.0
  connectivity_plus: ^3.0.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
